title: Bac Nguyen's Blog
name: "Bac Nguyen's Tech Blog"
author: Bac Nguyen
twitter_username:
baseurl: 
description: Document my learning notes.
profile_url: "http://bacnguyencong.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections:
  publications:
    output: true